version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
  vote:
    image: examplevotingappmaster_vote
    ports:
      - 5000:80
    volumes:
     - ./vote:/app 
    networks:
      - frontend
    depends_on:
      - redis
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
  result:
    image: examplevotingappmaster_result
    ports:
      - 5001:80
    volumes:
      - ./result:/app
    networks:
      - backend
    depends_on:
      - db
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  worker:
    image: examplevotingappmaster_worker
    networks:
      - frontend
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: replicated
      replicas: 1
      labels: [APP=VOTING]
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      
networks:
  frontend:
  backend:

volumes:
  db-data: